# encoding: utf-8
# This is an uploaded file generated by the CarrierWave gem
# it sets the type of storage and the directory to which files
# will be uploaded. These are then bound to a class in its model

class LogoUploader < CarrierWave::Uploader::Base
  storage :file

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
end
